from __future__ import annotations

from core.features.assembly import (
    Layer1FeatureInput,
    assemble_layer1_feature_records,
    validate_feature_availability,
)
from core.features.context_features import (
    CONTEXT_FEATURE_COLUMNS,
    compute_context_features,
    context_features_to_records,
)
from core.features.fundamentals_features import (
    FUNDAMENTAL_FEATURE_COLUMNS,
    compute_fundamentals_features,
    fundamentals_features_to_records,
)
from core.features.io import (
    feature_record_to_parquet_bytes,
    feature_records_to_parquet_bytes,
    parquet_bytes_to_feature_record,
    parquet_bytes_to_feature_records,
    read_feature_record,
    read_feature_records,
    write_feature_record,
    write_feature_records,
)
from core.features.loaders import load_fundamentals_frame, load_macro_frame, load_ohlcv_frame
from core.features.macro_features import (
    MACRO_FEATURE_COLUMNS,
    compute_macro_features,
    macro_features_to_records,
)
from core.features.market_features import (
    MARKET_FEATURE_COLUMNS,
    compute_market_features,
    market_features_to_records,
)
from core.features.news_preprocessing import (
    NewsPreprocessingConfig,
    news_sentiment_frame_to_records,
    preprocess_news_articles,
    records_to_news_sentiment_frame,
    split_article_sentences,
)
from core.features.news_relevance import (
    RELEVANCE_GATE_COLUMNS,
    NewsRelevanceGateConfig,
    NewsRelevanceGateResult,
    apply_news_relevance_gate,
)
from core.features.order_book_features import (
    ORDER_BOOK_FEATURE_COLUMNS,
    compute_order_book_features,
    order_book_features_to_records,
)
from core.features.regime_detection import (
    HMM_REGIME_COLUMNS,
    HMM_REGIME_FEATURE_COLUMNS,
    HMMRegimeConfig,
    HMMRegimeModel,
    emit_hmm_regime_features,
    fit_and_emit_hmm_regime_features,
    fit_hmm_regime_model,
    regime_features_to_records,
)
from core.features.regime_training import (
    HMM_TRAINING_COLUMNS,
    HMM_TRAINING_FEATURE_COLUMNS,
    build_hmm_training_frame,
    complete_hmm_training_matrix,
)
from core.features.sector_features import (
    DEFAULT_SECTOR_ETF_CONFIG_PATH,
    SECTOR_FEATURE_COLUMNS,
    SectorEtfConfig,
    compute_sector_features,
    load_sector_etf_config,
    sector_features_to_records,
)
from core.features.sentiment_features import (
    DEFAULT_SOURCE_CREDIBILITY_CONFIG_PATH,
    SENTIMENT_AGGREGATE_COLUMNS,
    SentimentScore,
    SentimentScorer,
    SourceCredibilityConfig,
    aggregate_sentiment_by_ticker_day,
    load_source_credibility_config,
    score_news_sentiment,
    sentiment_aggregates_to_records,
    sentiment_feature_records_from_scored_news,
    sentiment_feature_records_to_frame,
)
from core.features.text_topics import (
    EMBEDDING_COLUMNS,
    TOPIC_LABEL_COLUMNS,
    TextEmbeddingConfig,
    TopicModelConfig,
    compute_sentence_embeddings,
    compute_text_topics,
    compute_topic_labels,
    embedding_cache_key,
    feature_records_to_frame,
    sentence_identity,
    topic_labels_to_feature_records,
)

__all__ = [
    "CONTEXT_FEATURE_COLUMNS",
    "DEFAULT_SOURCE_CREDIBILITY_CONFIG_PATH",
    "DEFAULT_SECTOR_ETF_CONFIG_PATH",
    "EMBEDDING_COLUMNS",
    "FUNDAMENTAL_FEATURE_COLUMNS",
    "HMM_REGIME_COLUMNS",
    "HMM_REGIME_FEATURE_COLUMNS",
    "HMM_TRAINING_COLUMNS",
    "HMM_TRAINING_FEATURE_COLUMNS",
    "HMMRegimeConfig",
    "HMMRegimeModel",
    "Layer1FeatureInput",
    "MACRO_FEATURE_COLUMNS",
    "MARKET_FEATURE_COLUMNS",
    "NewsPreprocessingConfig",
    "NewsRelevanceGateConfig",
    "NewsRelevanceGateResult",
    "ORDER_BOOK_FEATURE_COLUMNS",
    "RELEVANCE_GATE_COLUMNS",
    "SECTOR_FEATURE_COLUMNS",
    "SENTIMENT_AGGREGATE_COLUMNS",
    "SentimentScore",
    "SentimentScorer",
    "SectorEtfConfig",
    "SourceCredibilityConfig",
    "TOPIC_LABEL_COLUMNS",
    "TextEmbeddingConfig",
    "TopicModelConfig",
    "aggregate_sentiment_by_ticker_day",
    "apply_news_relevance_gate",
    "assemble_layer1_feature_records",
    "build_hmm_training_frame",
    "complete_hmm_training_matrix",
    "compute_context_features",
    "compute_fundamentals_features",
    "compute_macro_features",
    "compute_market_features",
    "compute_order_book_features",
    "compute_sector_features",
    "compute_sentence_embeddings",
    "compute_text_topics",
    "compute_topic_labels",
    "context_features_to_records",
    "embedding_cache_key",
    "feature_record_to_parquet_bytes",
    "feature_records_to_parquet_bytes",
    "feature_records_to_frame",
    "emit_hmm_regime_features",
    "fit_and_emit_hmm_regime_features",
    "fit_hmm_regime_model",
    "fundamentals_features_to_records",
    "load_fundamentals_frame",
    "load_macro_frame",
    "load_ohlcv_frame",
    "load_sector_etf_config",
    "load_source_credibility_config",
    "macro_features_to_records",
    "market_features_to_records",
    "news_sentiment_frame_to_records",
    "order_book_features_to_records",
    "parquet_bytes_to_feature_record",
    "parquet_bytes_to_feature_records",
    "preprocess_news_articles",
    "read_feature_record",
    "read_feature_records",
    "regime_features_to_records",
    "records_to_news_sentiment_frame",
    "score_news_sentiment",
    "sector_features_to_records",
    "sentiment_aggregates_to_records",
    "sentiment_feature_records_from_scored_news",
    "sentiment_feature_records_to_frame",
    "sentence_identity",
    "split_article_sentences",
    "topic_labels_to_feature_records",
    "validate_feature_availability",
    "write_feature_record",
    "write_feature_records",
]
