name: Automate Project Status by Label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  update_project_status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
      repository-projects: write

    steps:
      - name: Move to Backlog
        if: github.event.label.name == 'status:backlog'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
          field-name: Status
          field-value: Backlog

      - name: Move to Ready
        if: github.event.label.name == 'status:ready'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
          field-name: Status
          field-value: Ready

      - name: Move to In Progress
        if: github.event.label.name == 'status:in-progress'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
          field-name: Status
          field-value: In Progress

      - name: Move to Blocked
        if: github.event.label.name == 'status:blocked'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
          field-name: Status
          field-value: Blocked

      - name: Move to Review
        if: github.event.label.name == 'status:review'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
          field-name: Status
          field-value: Review

      - name: Move to Done
        if: github.event.label.name == 'status:done'
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
          field-name: Status
          field-value: Done
